# Generated by Django 3.2.9 on 2021-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=200, unique=True)),
                ('from_user', models.CharField(max_length=200)),
                ('to_user', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('time_stamp', models.TimeField()),
                ('is_verify', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref_id', models.CharField(max_length=200, unique=True, verbose_name='userRefId')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('account_balance', models.FloatField(default=0.0, verbose_name='accountBalance')),
                ('pin', models.CharField(max_length=200, verbose_name='pin')),
            ],
            options={
                'db_table': '_user_',
            },
        ),
    ]
