# Generated by Django 3.2.9 on 2021-12-07 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='fullname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_model',
            name='identity_number',
            field=models.CharField(default=1, max_length=100, verbose_name='idnumber'),
            preserve_default=False,
        ),
    ]
