# Generated by Django 3.2.9 on 2021-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankservice', '0003_auto_20211211_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
