# Generated by Django 3.2.9 on 2021-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankservice', '0004_auto_20211215_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
