# Generated by Django 3.2.9 on 2021-12-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=200, unique=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
