# Generated by Django 3.2.9 on 2021-12-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddWallet',
            new_name='NewWallet',
        ),
    ]
