# Generated by Django 3.2.9 on 2021-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_addwallet_newwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwallet',
            name='ref_id',
            field=models.CharField(max_length=200),
        ),
    ]
